version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo "Supplied Vars"
      - echo "AWS_REGION=${AWS_REGION}"
      - echo "ECR_REGISTRY=${ECR_REGISTRY}"
      - echo "ECR_REPOSITORY_NAME=${ECR_REPOSITORY_NAME}"
      - echo "TASKDEF_IMAGETAG=${TASKDEF_IMAGETAG}"
      - echo "SSM_PATH=${SSM_PATH}"
      - echo "SCHEDULED_BUILD=${SCHEDULED_BUILD}"
       for debugging:
      - echo "Full Environment"
      - env | sort

      # Handle scheduled builds.
      # Basically, codepipeline sources a designated branch.
      # We obtain the semantic version for the current deployed application from
      # our deployment manifest in SSM ParameterStore.
      # We then check out that tag and proceed to build as usual.
      - |
        if [ -n "$SCHEDULED_BUILD" -a "$SCHEDULED_BUILD" == "true" ]; then
          echo 'This is a scheduled build'
          echo
          #echo "Available git tag refs:"
          #git --no-pager tag
          echo 'Get our "DEPLOYED_RELEASE" from deployment manifest'
          DEPLOYED_RELEASE=$(aws --output text ssm get-parameter --name $SSM_PATH --query Parameter.Value)
          echo "DEPLOYED_RELEASE=$DEPLOYED_RELEASE"
          echo "checkout DEPLOYED_RELEASE $DEPLOYED_RELEASE as a git tag"
          if [ "$?" != "0" ]; then
            echo "Attempt to run git checkout $DEPLOYED_RELEASE failed. Exiting!"
            exit 1
          fi
        fi

      - echo Logging in to Amazon ECR ...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      # is this the initial build?
      - |
        aws ecr describe-images \
          --repository-name ${ECR_REPOSITORY_NAME} \
          --image-ids imageTag=${TASKDEF_IMAGETAG} \
          2>&1 > /dev/null && INITIAL_BUILD="false" || INITIAL_BUILD="true"

      # Generate image tags
      #
      # get the first 7 chars of commit id provide by codebuild
      - COMMIT="${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}"
      - COMMIT=$(git rev-parse --short HEAD)
      # Get release or semantic version tags for commit
      - RELEASE_TAG=$(git tag --points-at $COMMIT | egrep "^v[0-9]+\.[0-9]+\.[0-9]+$" || echo '')
      - SEMVER_TAG=$(git tag --points-at $COMMIT | egrep "^v[0-9]+\.[0-9]+\.[0-9]_\w+$" || echo '')
      # Get any other tags for commit
      - OTHER_TAG=$(git tag --points-at $COMMIT | egrep -v "^v[0-9]+\.[0-9]+\.[0-9]+" || echo '')
      - |
        if [ -n "$RELEASE_TAG" ]; then
            IMAGE_TAG=$RELEASE_TAG
        elif [ -n "$SEMVER_TAG" ]; then
            IMAGE_TAG=$SEMVER_TAG
        else
            IMAGE_TAG=$OTHER_TAG
        fi
      - BUILD_DATE=$(TZ='America/Los_Angeles' date +"%Y%m%d.%H.%M.%S")

      # debug tags
      - echo "COMMIT=$COMMIT"
      - echo "RELEASE_TAG=$RELEASE_TAG"
      - echo "SEMVER_TAG=$SEMVER_TAG"
      - echo "OTHER_TAG=$OTHER_TAG"
      - echo "IMAGE_TAG=$IMAGE_TAG"
      - echo "BUILD_DATE=$BUILD_DATE"
      - echo "INITIAL_BUILD=$INITIAL_BUILD"
          

  build:
    commands:
      - echo "Running build - started on `date`"
      - echo Building the Docker image...
      - cd $CODEBUILD_SRC_DIR
      - docker buildx build --platform linux/amd64 -f Dockerfile.aws -t ${ECR_REPOSITORY_NAME}:${IMAGE_TAG} .


  post_build:
    commands:
      # Push the Docker image to the ECR repository.
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - cd $CODEBUILD_SRC_DIR
      - docker tag ${ECR_REPOSITORY_NAME}:${IMAGE_TAG} ${ECR_REGISTRY}/${ECR_REPOSITORY_NAME}:${IMAGE_TAG}
      - docker push ${ECR_REGISTRY}/${ECR_REPOSITORY_NAME}:${IMAGE_TAG}
      - docker tag ${ECR_REPOSITORY_NAME}:${IMAGE_TAG} ${ECR_REGISTRY}/${ECR_REPOSITORY_NAME}:${IMAGE_TAG}-${BUILD_DATE}
      - docker push ${ECR_REGISTRY}/${ECR_REPOSITORY_NAME}:${IMAGE_TAG}-${BUILD_DATE}
      - |
        if [ "$INITIAL_BUILD" == "true" ]; then 
          docker tag ${ECR_REPOSITORY_NAME}:${IMAGE_TAG} ${ECR_REGISTRY}/${ECR_REPOSITORY_NAME}:${TASKDEF_IMAGETAG}
          docker push ${ECR_REGISTRY}/${ECR_REPOSITORY_NAME}:${TASKDEF_IMAGETAG}
        fi

