# ---- Base image ----
FROM nginx:stable

# Set working directory
WORKDIR /app

COPY legacy_e_files ./legacy_e_files
# Copy nginx config
COPY nginx.conf /etc/nginx/nginx.conf

# Remove default nginx site
RUN rm -f /etc/nginx/sites-enabled/default

# Create log + run directories
RUN mkdir -p /var/run/nginx

# Document the exposed port
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
