# ---- Base image ----
FROM public.ecr.aws/amazonlinux/amazonlinux:2023

RUN dnf install -y nginx && dnf clean all

# Set working directory
WORKDIR /app

COPY legacy_e_files ./legacy_e_files
COPY nginx.conf /etc/nginx/nginx.conf

# Create log + run directories
RUN mkdir -p /var/run/nginx

# Document the exposed port
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
