worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    types {
        text/plain yaml yml;
    }
    default_type  application/octet-stream;

    log_format  main  '$remote_addr "$http_x_forwarded_for" [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent"';

    access_log  /var/log/nginx/access.log  main;
    error_log /var/log/nginx/error.log warn;

    sendfile        on;

    keepalive_timeout  65;


    server {
        listen       8080;
        server_name  localhost;


        location = /e/naan_request {
            return 302 https://forms.gle/2a8HQUNJRAcvq5UGA;
        }

        location ~ ^/e/pub/?(.*)$ {
            return 301 https://cdluc3.github.io/naan_reg_priv/$1;
        }

        location /e/ {
            root /app/legacy_e_files;
        }


        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
